# 08.19.2025
#my first project on pythin snake

print("hello")
print()
print("what is your name?")
print()
name = input()        #this is where the program stops for me to enter somthing
print()
print("nice to meet you,",name)    #uses the name and prints it back
print()
print("what grade are you in?")
print()
grade = input()   # meed to put my grade
print()
print("WOW thats cool :)have fun in",grade)
print()
print("What country are you from?",name)
print()
country = input()
print()
print("that country is a nice place i wish i could go to,",country)
print()
print("😁")
print()
print("any thing else you want me to know?")
print()
question = input()
print()
print("Ok")
print()
print("Who is your advisor?")
print()
Advisor = input()
print()
print("Nice how is",Advisor "?")
print()
howadvisor= input()
print()
print("Thats nice to know")
print()
print("where are you going for the global citizenship week")
print()
trip = input()
print()
print("ooo that sounds fun have fun in,",trip, "😊")